-- Creates tables for knowledge uploads + embedding job queue.
-- Target: Oracle Database (compatible with VECTOR type usage already present).

-- Uploaded file registry
CREATE TABLE edge_demo_knowledge_file (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR2(64) NOT NULL,
  filename VARCHAR2(255) NOT NULL,
  storage_path VARCHAR2(1024) NOT NULL,
  bytes NUMBER,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX edge_demo_knowledge_file_cat_idx ON edge_demo_knowledge_file(category);

-- Embedding job queue
CREATE TABLE edge_demo_knowledge_job (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id NUMBER NOT NULL,
  status VARCHAR2(16) NOT NULL,
  progress_pct NUMBER DEFAULT 0 NOT NULL,
  message VARCHAR2(1000),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  started_at TIMESTAMP,
  finished_at TIMESTAMP,
  CONSTRAINT edge_demo_knowledge_job_file_fk FOREIGN KEY (file_id) REFERENCES edge_demo_knowledge_file(id)
);

CREATE INDEX edge_demo_knowledge_job_status_idx ON edge_demo_knowledge_job(status);
