-- Create knowledge upload registry + embedding job queue for the configured prefix.
-- This migration is safe to apply on existing schemas (uses PL/SQL blocks to ignore ORA-00955).
-- Substitute the prefix at runtime using the migration runner (DB_TABLE_PREFIX).

-- NOTE: the token ${PREFIX} is replaced by backend/scripts/apply_migrations.py

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ${PREFIX}_knowledge_file (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category VARCHAR2(64) NOT NULL,
      filename VARCHAR2(255) NOT NULL,
      storage_path VARCHAR2(1024) NOT NULL,
      bytes NUMBER,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_kf_cat_idx ON ${PREFIX}_knowledge_file(category)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ${PREFIX}_knowledge_job (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      status VARCHAR2(16) NOT NULL,
      progress_pct NUMBER DEFAULT 0 NOT NULL,
      message VARCHAR2(1000),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      started_at TIMESTAMP,
      finished_at TIMESTAMP
    )
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_kj_status_idx ON ${PREFIX}_knowledge_job(status)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ${PREFIX}_knowledge_job_file (
      job_id NUMBER NOT NULL,
      file_id NUMBER NOT NULL,
      CONSTRAINT ${PREFIX}_kjf_job_fk FOREIGN KEY (job_id) REFERENCES ${PREFIX}_knowledge_job(id),
      CONSTRAINT ${PREFIX}_kjf_file_fk FOREIGN KEY (file_id) REFERENCES ${PREFIX}_knowledge_file(id)
    )
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_kjf_job_idx ON ${PREFIX}_knowledge_job_file(job_id)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/
