-- Creates the prefixed embedding table if it does not exist.
-- Uses ${PREFIX} token which is replaced by backend/scripts/apply_migrations.py.

DECLARE
  e_table_missing EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_missing, -942);
BEGIN
  EXECUTE IMMEDIATE 'SELECT 1 FROM ${PREFIX}_EMBEDDING WHERE 1 = 0';
EXCEPTION
  WHEN e_table_missing THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE ${PREFIX}_EMBEDDING (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        text CLOB,
        embedding_vector VECTOR,
        chapter VARCHAR2(200),
        section VARCHAR2(200),
        source VARCHAR2(400)
      )
    ]';
END;
/

-- Basic indexes for metadata filtering.
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ${PREFIX}_EMB_SOURCE_IDX ON ${PREFIX}_EMBEDDING (source)';
EXCEPTION
  WHEN e_already_exists THEN
    NULL;
END;
/

DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ${PREFIX}_EMB_CHAPTER_IDX ON ${PREFIX}_EMBEDDING (chapter)';
EXCEPTION
  WHEN e_already_exists THEN
    NULL;
END;
/

DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ${PREFIX}_EMB_SECTION_IDX ON ${PREFIX}_EMBEDDING (section)';
EXCEPTION
  WHEN e_already_exists THEN
    NULL;
END;
/
