-- Creates restaurant + menu tables for the configured prefix.
-- Uses ${PREFIX} token which is replaced by backend/scripts/apply_migrations.py.
-- Safe to apply multiple times (ignores ORA-00955 name already used).

-- Restaurants (basic location + contact)
DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ${PREFIX}_restaurant (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR2(200) NOT NULL,
      image_url VARCHAR2(1000),
      address_line1 VARCHAR2(255),
      address_line2 VARCHAR2(255),
      city VARCHAR2(120),
      state VARCHAR2(120),
      country VARCHAR2(120),
      postal_code VARCHAR2(32),
      latitude NUMBER(10,7),
      longitude NUMBER(10,7),
      phone VARCHAR2(64),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

-- If the table already existed (older migration applied), add the column if missing.
DECLARE
  e_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_col_exists, -1430);
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ${PREFIX}_restaurant ADD (image_url VARCHAR2(1000))';
EXCEPTION
  WHEN e_col_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_rest_city_idx ON ${PREFIX}_restaurant(city)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_rest_name_idx ON ${PREFIX}_restaurant(name)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

-- Menu items (items offered by a restaurant)
DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ${PREFIX}_menu_item (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      restaurant_id NUMBER NOT NULL,
      name VARCHAR2(200) NOT NULL,
      image_url VARCHAR2(1000),
      description CLOB,
      category VARCHAR2(120),
      price NUMBER(10,2),
      currency CHAR(3) DEFAULT 'USD' NOT NULL,
      available CHAR(1) DEFAULT 'Y' NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT ${PREFIX}_mi_rest_fk FOREIGN KEY (restaurant_id) REFERENCES ${PREFIX}_restaurant(id)
    )
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

-- If the table already existed (older migration applied), add the column if missing.
DECLARE
  e_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_col_exists, -1430);
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ${PREFIX}_menu_item ADD (image_url VARCHAR2(1000))';
EXCEPTION
  WHEN e_col_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_mi_rest_idx ON ${PREFIX}_menu_item(restaurant_id)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_mi_cat_idx ON ${PREFIX}_menu_item(category)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/

DECLARE
  e_name_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_name_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX ${PREFIX}_mi_avail_idx ON ${PREFIX}_menu_item(available)
  ]';
EXCEPTION
  WHEN e_name_exists THEN NULL;
END;
/
